export const RULE_ADDED='RULE_ADDED';
export const RULE_TEXT_UPDATED='RULE_TEXT_UPDATED';
export const TILE_CLICKED='TILE_CLICKED';
export const REQUEST_GITHUB_DATA='REQUEST_GITHUB_DATA';
export const FETCH_GITHUB_DATA='FETCH_GITHUB_DATA';