export const RULE_ADDED='RULE_ADDED';
export const RULE_TEXT_UPDATED='RULE_TEXT_UPDATED';
export const TILE_CLICKED='TILE_CLICKED';
export const GITHUB_FETCH_USER_DATA='GITHUB_FETCH_USER_DATA';
export const GITHUB_FETCH_REPOSITORIES='GITHUB_FETCH_REPOSITORIES';